// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using HexaGen.Runtime;

namespace Hexa.NET.SDL3
{
	public enum SDLGPUColorComponentFlags : byte
	{
		R = (byte)(1u<<0),
		G = (byte)(1u<<1),
		B = (byte)(1u<<2),
		A = (byte)(1u<<3),
	}
}
