// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using HexaGen.Runtime;

namespace Hexa.NET.SDL3
{
	public enum SDLInitFlags : uint
	{
		Timer = 0x00000001u,
		Audio = 0x00000010u,
		Video = 0x00000020u,
		Joystick = 0x00000200u,
		Haptic = 0x00001000u,
		Gamepad = 0x00002000u,
		Events = 0x00004000u,
		Sensor = 0x00008000u,
		Camera = 0x00010000u,
		Gamecontroller = Gamepad,
	}
}
