// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using HexaGen.Runtime;

namespace Hexa.NET.SDL3
{
	public enum SDLMouseButtonFlags : uint
	{
		Left = 1,
		Middle = 2,
		Right = 3,
		X1 = 4,
		X2 = 5,
		//Lmask = SDL_BUTTON(Left),
		//Mmask = SDL_BUTTON(Middle),
		//Rmask = SDL_BUTTON(Right),
		//X1Mask = SDL_BUTTON(X1),
		//X2Mask = SDL_BUTTON(X2),
	}
}
