name: Build and Upload SDL2 Artifacts

on: [workflow_dispatch]

jobs:
  build:
    uses: JunaMeinhold/cmake-actions/.github/workflows/cmake.yml@v1.x.x
    with:
      lib-name: SDL2
      repo: libsdl-org/SDL
      repo-tag: 6c7fc09feec2efc4095fcd06330c498dad19974d
      repo-path: SDL
      cmake-flags: "-DCMAKE_BUILD_TYPE=Release -DSDL_STATIC=OFF -DSDL_SHARED=ON"
      cmake-flags-windows: "-DCMAKE_SYSTEM_VERSION=10.0.26100.0"
      ndk-version: "26.3.11579264"
      android-api: "21"
      build-output-dir: artifacts
      bin-name-osx: libSDL2-2.0.dylib
      bin-name-linux: libSDL2-2.0.so
      bin-name-android: libSDL2.so
      bin-name-windows: Release/SDL2.dll
      bin-name-osx-normalized: libSDL2.dylib
      bin-name-linux-normalized: libSDL2.so
      bin-name-android-normalized: libSDL2.so
      bin-name-windows-normalized: SDL2.dll
      linux-deps: "build-essential cmake libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxinerama-dev libxss-dev libwayland-dev libwayland-egl-backend-dev libdbus-1-dev libudev-dev libgles2-mesa-dev libegl1-mesa-dev libgl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev ccache libjack-jackd2-dev libdrm-dev libpipewire-0.3-dev libvulkan-dev libdecor-0-dev qtwayland5 libxkbcommon-dev libsndio-dev"
      android-deps: "build-essential cmake ninja-build"

  create-pr:
    uses: JunaMeinhold/cmake-actions/.github/workflows/create-pr.yml@v1.x.x
    needs: [build]
    with:
      lib-name: SDL2
      lib-version: release-2.32.8
      pr-branch: sdl2-artifacts-branch
      pr-base-branch: master
      pr-reviewers: JunaMeinhold
